# Generated by Django 4.0.2 on 2022-02-16 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_comment_reply_category_author_category_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forbiddenword',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forbiddenword',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
