# Generated by Django 4.0.2 on 2022-02-17 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_forbiddenword_author_forbiddenword_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subscribes',
            field=models.ManyToManyField(related_name='category_subscribes', to=settings.AUTH_USER_MODEL),
        ),
    ]
