# Generated by Django 4.0.2 on 2022-02-17 14:18

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('blog', '0006_posttags_remove_post_tags_post_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag_name',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='PostTags',
        ),
    ]
