# Generated by Django 4.0.2 on 2022-02-17 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_post_tag_name_post_tags_delete_posttags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
