<<<<<<< HEAD
# Generated by Django 4.0.2 on 2022-02-14 01:33
=======
# Generated by Django 4.0.2 on 2022-02-14 13:33
>>>>>>> c73fa93995d15cab93d8a239c77ebeb1e7c99d02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('blog', '0007_alter_post_content_alter_post_image'),
=======
        ('blog', '0007_post_likes'),
>>>>>>> c73fa93995d15cab93d8a239c77ebeb1e7c99d02
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Image',
<<<<<<< HEAD
            field=models.ImageField(blank=True, null=True, upload_to='blog/static/img'),
=======
            field=models.ImageField(null=True, upload_to=''),
>>>>>>> c73fa93995d15cab93d8a239c77ebeb1e7c99d02
        ),
    ]
