<<<<<<< HEAD
# Generated by Django 4.0.2 on 2022-02-14 01:49
=======
# Generated by Django 4.0.2 on 2022-02-14 13:35
>>>>>>> c73fa93995d15cab93d8a239c77ebeb1e7c99d02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Image',
<<<<<<< HEAD
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
=======
            field=models.ImageField(blank=True, null=True, upload_to=''),
>>>>>>> c73fa93995d15cab93d8a239c77ebeb1e7c99d02
        ),
    ]
