# Generated by Django 4.0.2 on 2022-02-15 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_category_subscribers_alter_post_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='subscribers',
            new_name='subscribes',
        ),
    ]
