# Generated by Django 4.0.2 on 2022-02-14 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_likes'),
        ('blog', '0010_alter_post_image'),
    ]

    operations = [
    ]
