# Generated by Django 4.0.2 on 2022-02-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
