# Generated by Django 4.0.2 on 2022-02-15 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_post_likes'),
        ('blog', '0017_alter_post_date'),
    ]

    operations = [
    ]
