# Generated by Django 4.0.2 on 2022-02-15 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0019_category_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="author",
            field=models.ForeignKey(
                null=True,
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
