# Generated by Django 4.0.2 on 2022-02-16 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_content_alter_post_image'),
        ('blog', '0009_rename_subscribers_category_subscribes'),
        ('blog', '0022_alter_category_date'),
    ]

    operations = [
    ]
